// ============================================================
// Simulation engine — deliberately NOT an AI/LLM call.
// This is a plain rule-based script: fixed probabilities, bounded
// random walks, and the routing.js flowchart logic. Same inputs +
// same RNG seed always produce the same class of behavior, so it's
// reproducible and auditable — nothing here is "generated by AI".
// ============================================================
const { pool } = require('../db/pool');
const { runRoutingCycle } = require('./routing');

const TICK_INTERVAL_MS = 15_000;      // how often the simulation advances
const SNAPSHOT_INTERVAL_TICKS = 4;    // snapshot every 4th tick (~every 60s)
const BED_CHANGE_PROBABILITY = 0.35;  // chance a facility's occupancy shifts this tick
const AMBULANCE_DRIFT_DEGREES = 0.01; // small step for "moving" ambulance markers

let tickCount = 0;

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * Nudges each facility's occupied-bed count up or down by a small bounded
 * amount, with a fixed probability of "no change" — a plain weighted
 * random walk, not a model prediction.
 */
async function driftFacilityOccupancy() {
  const { rows: facilities } = await pool.query(
    `SELECT id, total_beds, occupied_beds, ST_X(location) AS lon, ST_Y(location) AS lat
     FROM facilities`
  );

  const results = [];
  for (const facility of facilities) {
    if (Math.random() < BED_CHANGE_PROBABILITY) {
      const delta = randomInt(-3, 4); // slightly biased upward to occasionally trip the RED threshold
      let newOccupied = facility.occupied_beds + delta;
      newOccupied = Math.max(0, Math.min(facility.total_beds, newOccupied));

      await pool.query(`UPDATE facilities SET occupied_beds = $1 WHERE id = $2`, [
        newOccupied,
        facility.id,
      ]);
      facility.occupied_beds = newOccupied;
    }

    // routing.js owns the actual status/dispatch decision — the engine
    // only ever perturbs the raw bed counts.
    const cycleResult = await runRoutingCycle(facility);
    results.push(cycleResult);
  }
  return results;
}

/**
 * Moves EN_ROUTE ambulances a small step toward their assigned facility,
 * and occasionally frees an AVAILABLE ambulance to simulate patrol drift.
 * Pure coordinate arithmetic — no external calls.
 */
async function driftAmbulances() {
  const { rows: ambulances } = await pool.query(
    `SELECT a.id, a.status, a.assigned_facility_id,
            ST_X(a.location) AS lon, ST_Y(a.location) AS lat,
            ST_X(f.location) AS f_lon, ST_Y(f.location) AS f_lat
     FROM ambulances a
     LEFT JOIN facilities f ON f.id = a.assigned_facility_id`
  );

  for (const amb of ambulances) {
    if (amb.status === 'EN_ROUTE' && amb.f_lon != null) {
      const dLon = amb.f_lon - amb.lon;
      const dLat = amb.f_lat - amb.lat;
      const dist = Math.sqrt(dLon * dLon + dLat * dLat);

      if (dist < AMBULANCE_DRIFT_DEGREES) {
        // arrived
        await pool.query(
          `UPDATE ambulances SET status = 'AT_SCENE', location = ST_SetSRID(ST_MakePoint($1,$2),4326), updated_at = now() WHERE id = $3`,
          [amb.f_lon, amb.f_lat, amb.id]
        );
      } else {
        const stepLon = amb.lon + (dLon / dist) * AMBULANCE_DRIFT_DEGREES;
        const stepLat = amb.lat + (dLat / dist) * AMBULANCE_DRIFT_DEGREES;
        await pool.query(
          `UPDATE ambulances SET location = ST_SetSRID(ST_MakePoint($1,$2),4326), updated_at = now() WHERE id = $3`,
          [stepLon, stepLat, amb.id]
        );
      }
    } else if (amb.status === 'AT_SCENE' && Math.random() < 0.4) {
      // becomes available again after a bounded dwell
      await pool.query(
        `UPDATE ambulances SET status = 'AVAILABLE', assigned_facility_id = NULL, updated_at = now() WHERE id = $1`,
        [amb.id]
      );
    }
  }
}

async function takeSnapshot() {
  const { rows: facilities } = await pool.query(`SELECT * FROM facility_occupancy`);
  const { rows: ambulances } = await pool.query(`SELECT * FROM ambulances`);
  await pool.query(
    `INSERT INTO state_snapshots (facilities_json, ambulances_json) VALUES ($1, $2)`,
    [JSON.stringify(facilities), JSON.stringify(ambulances)]
  );
}

/**
 * One full simulation tick. Returns the routing results so the caller
 * (server.js) can broadcast only what changed.
 */
async function tick() {
  tickCount += 1;
  const routingResults = await driftFacilityOccupancy();
  await driftAmbulances();

  if (tickCount % SNAPSHOT_INTERVAL_TICKS === 0) {
    await takeSnapshot();
  }

  return routingResults;
}

function startSimulation(onTick) {
  return setInterval(async () => {
    try {
      const results = await tick();
      onTick(results);
    } catch (err) {
      // A failed tick must never kill the interval — log and retry next tick.
      console.error('[simulation] tick failed', err.message);
    }
  }, TICK_INTERVAL_MS);
}

module.exports = { startSimulation, tick, TICK_INTERVAL_MS };
